# Generated by Django 2.2.11 on 2021-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Yt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField()),
                ('views', models.IntegerField()),
                ('username', models.TextField()),
            ],
        ),
    ]
