# Generated by Django 2.2.11 on 2021-05-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yt',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
