# Generated by Django 2.2.11 on 2021-05-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_yt_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField()),
                ('username', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
