# Generated by Django 2.2.11 on 2021-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed',
            name='time',
            field=models.TextField(),
        ),
    ]
