# Generated by Django 2.2.11 on 2021-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_yt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yt',
            name='category',
            field=models.TextField(default='Vlog'),
        ),
    ]
